FROM mcr.microsoft.com/devcontainers/python:1-3.12-bullseye

RUN pip3 --disable-pip-version-check --no-cache-dir install \
    "matplotlib==3.8.3" \
    "numpy==1.26.4" \
    "scipy==1.12.0" \
    "scikit-image==0.22.0" \
    "tifffile==2024.2.12" \
    "pillow==10.2.0" \
    "ipykernel==6.29.2"