name: Update configuration

on:

  workflow_dispatch:

  schedule:
    - cron: '0 1 * * 1'  ## At 01:00 AM on every Monday


jobs:

  pull_upstream:

    # To enable updates, set this to the name of your repository:
    if: github.repository == 'kostrykin/python-learning-codespace'

    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:

      - uses: actions/checkout@v4

      - uses: fregante/setup-git-user@v2

      - name: Create branch for merging
        shell: bash
        run: |
          git checkout -b pull_upstream

      - name: Add remote for upstream
        shell: bash
        run: |
          git remote add upstream https://github.com/kostrykin/python-learning-codespace
          git fetch upstream

      - name: Merge (squash)
        continue-on-error: true
        shell: bash
        run: |
          git merge upstream/master --allow-unrelated-histories --squash

      - name: List files with merge conflicts
        shell: bash
        run: |
          echo "Please resolve merge conflicts within the following files:" >> .pr-body.md
          git diff --name-only --diff-filter=U --relative | awk '{print "- " $0}' >> .pr-body.md

      - name: Commit
        id: commit
        continue-on-error: true
        shell: bash
        run: |
          git commit -a -m "Update configuration"

      - name: Push
        if: steps.commit.outcome == 'success'
        shell: bash
        run: |
          git push origin pull_upstream
      
      - name: Create pull request
        if: steps.commit.outcome == 'success'
        shell: bash
        run: |
          gh pr create --fill --body-file ".pr-body.md" --base ${{ github.ref_name }} --head pull_upstream
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}