name: Update configuration

on:

  workflow_dispatch:

  schedule:
    - cron: '0 1 * * 1'  ## At 01:00 AM on every Monday


jobs:

  pull_upstream:

    # To enable updates, set this to the name of your repository:
    if: github.repository == 'kostrykin/python-learning-codespace'

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - uses: actions/checkout@v4

      - uses: fregante/setup-git-user@v2

      - name: Create branch for merging
        shell: bash
        run: |
          git checkout -b pull_upstream

      - name: Pull from upstream
        shell: bash
        run: |
          git remote add upstream https://github.com/kostrykin/python-learning-codespace
          git fetch upstream
          git merge upstream/master --allow-unrelated-histories
          git commit --allow-empty -a -m "Update configuration"
          git push origin pull_upstream
      
      - name: Create pull request
        shell: bash
        run: |
          gh pr create --fill --head pull_upstream
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}